### ISSUE TITLE
Preparation 1: Funny Stories

### ISSUE THREAD

**Issue by dykesb** [STA518-01-Fall20/community#1]
Tell a funny story of a time your teacher or professor did not understand how to use technology.

I'll start things off! In grad school when I was student teaching, I *forgot* that the projector screen was down and started circling items from the slide that I was projecting... with the dry erase marker that I was holding. Dry eraser markers erase very easily from a whiteboard, but not so much so from a projector screen 🤦 

I **always** double-check that the screen is up now.

**Comment by lefflerl** [comment]
During my undergrad I had two professors do the same thing, they also **always** double checked the screen after that. Another professor during undergrad went to show us a [Youtube](https://www.youtube.com) video and didn't realize they could skip the ad, so we just watched a 1 minute or so ad. Made sure to tell him after class so he doesn't do that again.

**Comment by eboven22** [comment]
During my undergrad, I had the same professor in two different classes and two different rooms. In one room, he would walk backward while pointing to the board, at least once a week, he would _back into_ the **trashcan** along the wall. In the other room, he would _back into_ the **chair** sitting in a corner if that screen was up.

**Comment by eboven22** [comment]
I guess it's not necessarily that he didn't know how to use technology but how he used it. Anyway, a teacher in high school would make the projector project the notes into the _corner of the classroom_ and call them **3D notes** and make us take notes with the projector like that. It's funny now.

**Comment by phillisd37** [comment]
I had a teacher at MSU that absolutely refused to do anything with technology. She would write out her Statistics notes on a projector screen, you know the ones that had the transparent sheets and a light projecting the writing to a board, something that I haven't seen since middle school.

**Comment by phillisd37** [comment]
I had a professor that **refused** to use any sort of technology. She would use the old time projector that had transparent paper that was written down and projected to the board, it looked like [this!](https://www.pinterest.com/pin/136445063685082979/) I haven't seen one of these since elementary school.

**Comment by stawinski-mike** [comment]
This small error still happens to all professors every once in while: when they show a video or Youtube clip **not knowing** the volume is all the way up.  Usually catches everyone off guard and makes the room jump at first, then the professor quickly scrambles to adjust the clip's volume to a more _tolerable_ level.

**Comment by karkipr** [comment]
The projectors were installed for the first time in the classes in my junior school and one of the teachers(who was older) wanted to try out and transition from the old chalkboard/chalk situation. We waited for good 5 minutes until he figured what switch went where and finally gave up and sought help.

**Comment by gellertl** [comment]
Playing videos *with the sound* has been an issue for many of my professors. When I first started college I had a professor who wanted to show a video to introduce that class to some of the basic ideas of the course. After about 5 minutes of **no sound** and the professor tweaking as many of the sound controls as possible, IT came to fix it. The computer volume was on mute.

**Comment by rossmann8** [comment]
I had a professor in undergrad who did not know the wifi was turned off on her laptop while trying to project a quiz onto the screen. She could not figure it out for *at least* fifteen minutes and was **very embarrassed** when she solved the issue.

**Comment by kelleyc11** [comment]
I had a professor who had IT come mid-class because he was so **frustrated**. But, IT said they `couldn't` fix it so he asked him what his job was and told the entire class to go home and we _### weren't_ having class until they fixed the issue...

**Comment by evanwhitmore** [comment]
My first semester here at _**GVSU**_ I had a Chem 109 lecture with 135 students. As you can imagine, the people in the back had to sit very far away. Much like the story shared by @phillisd37 , this particular professor refused to use the ELMO's provided or the 3 huge screens when doing practice problems, instead she insisted on using the classic shadow-based overhead projectors

**Comment by pcar13** [comment]
In high school I took a film class. There was one day where we were watching movie trailers and discussing the techniques used to make films appealing. A teacher from next door was having some *technical issues*, so my teacher went to help. He put on a trailer for some random movie on the projector and left. We were watching the trailer on YouTube, and my teacher had **auto play** on. Well he took longer than he intended, so when he walked in the trailer for "Fifty Shades Darker" was just about done playing.

**Comment by mennengm** [comment]
I don't have many funny stories involving *this* type of situation, but **just today** my professor didn't realized until three-quarters of the way through our zoom meeting that she wasn't recording it. One professor also mentioned that he doesn't like recording zoom meetings with cameras on, because *"everything on the internet **stays** on the internet"*. I think he just doesn't want to end up on TikTok.

**Comment by jenpel** [comment]
In my intro to stats course I had a professor who could not figure out how to work the **projector**. One day she wanted to demonstrate how to use the calculator for a specific activity and wanted to use the projector. She spent probably 10 minutes trying to figure out how to get it to display properly and never did get it. That evening she posted a **handout with calculator instructions**. We used handouts for the rest of the semester and she never attempted to use the projector again.

**Comment by schemand** [comment]
It seems like a lot of professors are still grasping the volume situation between their computers and projectors. More than enough times my professors have not been able to get sound on videos **but** when they finally figure out how to turn it on, it about blasts all the students eardrums until they then figure out how to turn it *down* again.

**Comment by artyclark1234** [comment]
I don't have any specific stories but there are **two** things that professors seem to do routinely. First, without a doubt, they forget to turn their microphones on. It can be comical sometimes to see the professor's reaction after they realize they've been lecturing for five minutes and having to redo it. Secondly, they almost assume that they are always sharing their _screen_. It's like they don't know they remotely have to push the button sometimes. I wish we could do in-person classes :(.

**Comment by daytonmo** [comment]
I can't think of a specific time where a prof struggled, but I can think of __many__ times where I have struggled with technology when leading a class. One of those times happened to be on my first day of facilitating a stats 215 course. For some reason, I could not get the projector to display anything that the computer was displaying, and all of my materials for the first day required use of the projector (powerpoint, Kahoot!, etc.). I ended up having to leave the classroom and ask for a profs help. He managed to get everything squared away, but this was like 10 minutes into the 50 minute course and I had shown up 10 minutes early to get everything set up for day one. Lovely. Let's just say that I did not use the projector for a bit afterwards. I very much sympathize with the prof discussed in @jenpel 's story because I also struggled to display a calculator demonstration using an ELMO and unfortunately did end up having to send out a written calculator handout.

**Comment by nomulac** [comment]
I've had a Professor who wanted to give us a test which was Autograded by the platform in which he posted it, but, later realized that he used surveys as the method of giving us the test for which *users are **anonymous*** and later had to convince the **whole class to redo the test**

**Comment by jmili84** [comment]
No **particularly** exciting technology incidents stand out at the moment.  I did have a professor ***just*** last semester articulate to the entire class that an online final exam was on a certain day, but the link in Blackboard did not show up at the time that they indicated it would.  I was messaging with another person in the class just to make sure something wasn't up on my end when the test never showed up.  The professor forgot to set the exam to go live in Blackboard at the appropriate time and was unresponsive to emails the entire time the test was supposed to be taken.  We all got a message the next day indicating that the exam would be available later that day.

**Comment by toledo-a** [comment]
I had a professor who **could not** get the projector screen to stay *completely* down on the first day, so part of the screen was cut off during most of the lecture.

**Comment by GibbonKr** [comment]
_In Elementary School, my teacher **pulled in the tv** into our classroom and tried to start up the movie that we were to watch for class._ She forgot to  check if everything was plugged in (**the DVD player was not**) and then the whole class had to watch her struggle to make everything work. It took her 30 mins and she had brought in another teacher to help.

**Comment by calvin-andrews** [comment]
During a class at community college, the teacher wanted us to watch a video in class. However, they could not get the _sound to work out of the speakers_, so we had to listen to the whole thing through there laptop/desktop computer speakers. It was extremely hard to hear and I am not sure that anyone got a **good** understanding of the video.

**Comment by reevesjo** [comment]
When I was in high school, my AP Government teacher was an _old, senile man_ who knew little to nothing about computers and technology (but was very knowledgeable about government and history). One day, he asked our class how to change the background image on his computer to something related to **US Government**, so myself and some peers uploaded a photo of "Obama at the beach" which was rather humorous (especially because he didn't know how to change it back).

**Comment by faskij** [comment]
When I was in high school, I bought my first smart phone. It was an [LG G3](https://www.gsmarena.com/lg_g3-6294.php). I was a little trouble maker when I got bored in class and this phone had an app that could control electronics as a universal remote. Our biology teacher, who had a great sense of humor, used a remote control projector for class. If it was a slow day, sometimes I would turn the projector off and on to amuse the class. He had no idea what was going on. Please don't tell Mr. B. He probably wouldn't care anyways. He went on to help create **RED BOX**, so he might not even remember me.

**Comment by Anthony-Picard** [comment]
If you are anything like me, you found it hilarious when the substitute teachers struggled to play the movie that you were going to watch that day. Well flash-forward to six months out of undergrad and **I'm that guy!** I ended up having to swallow my pride and one of the students solved the issue...the HDMI cable was not plugged in. I learned a very important lesson about *karma* that day.

**Comment by Abigail-Czinder** [comment]
I had a teacher do something like this! It was in highschool and he started writing with the whiteboard markers right on the **smartboard**! They glow _really_ bright when used on a screen haha
