### ISSUE TITLE
Activity 1.3 Matrix Question

### ISSUE THREAD

**Issue by rossmann8** [STA518-01-Fall20/community#11]
On line 112 of activity 1.3, the r chunk where we are to manipulate our matrix, we are supposed to subtract the "evens" vector from the first column. When I run:

```{r}
my_matrix = matrix(fourth, ncol = 5)   #fourth is just my variable after the secret code instructions
evens <- seq(2,382,2)
my_matrix <- sweep(my_matrix[,1], 2, evens, "-")
```

I get the error: STATS is longer than the extent of 'dim(x)[MARGIN]'Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0

I don't understand how these can be different lengths. My matrix has 191 rows, and I have confirmed that my evens list has a length of 191.

Could you let me know what I am doing wrong / point me in the right direction?

**Comment by dykesb** [comment]
I haven't used the `sweep() ` function before so I'm not too sure what the arguments are, but try:

```
my_matrix[, 1] <- my_matrix[, 1]  -  evens
```

instead of 

```
my_matrix <- sweep(my_matrix[,1], 2, evens, "-")
```

**Comment by dykesb** [comment]
Here is a response I gave to the other section that might be helpful for this issue too:

In the [Programming Basics](https://rstudio.cloud/learn/primers/1.2) primer, you learned about extracting specific items using the square brackets (`[ ]`). For example, if you have a vector that is a sequence of number 1 to 10:

```
> vec <- 1:10
> vec

[1]  1  2  3  4  5  6  7  8  9 10
```

You could show the 2nd, 5th, and 8th values by doing:

```
> vec[c(2, 5, 8)]

[1] 2 5 8
```

In matrices, you can do something similar where you can specify the row, the column, or both. If you have a 2 rows x 5 columns matrix:

```
> mat <- matrix(vec, ncol = 5)
> mat

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
```

You can pull just the second column by doing:

```
> mat[ ,2]

[1] 3 4
```

or the first row by doing:

```
mat[1,]

[1] 1 3 5 7 9
```

If I wanted to subtract "1" from every value in the second column and replace that in my matrix, I could do:

```
> mat[ ,2] <- mat[ ,2] - 1
> mat

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    5    7    9
[2,]    2    3    6    8   10
```

If I wanted to subtract a vector `vec2 <- c(10, 8, 6, 4, 2)` from every value in the first row and replace that in my matrix, I could do:

```
> vec2 <- c(10, 8, 6, 4, 2)
> vec2

[1] 10  8  6  4  2

> mat[ 1,] <- mat[ 1,] - vec2
> mat

     [,1] [,2] [,3] [,4] [,5]
[1,]   -9   -6   -1    3    7
[2,]    2    3    6    8   10
```

That should help, but I can find some web resources if you'd like more examples.
