### ISSUE TITLE
Activity 1.3 sqrt() produces NaN values

### ISSUE THREAD

**Issue by phillisd37** [STA518-01-Fall20/community#12]
Hi Everyone!

Our group was working on task #4 questions 5-11. We thought we were able to convert the martix back into a vector however when we proceeded to step 12, we got a lot of NaN numbers (due to the fact that we had a ton of negative numbers) and step 13 says to round to the nearest whole number when they already were whole. Does anyone know what we did incorrectly? or is this what we're supposed to get?

I have a feeling it may be when we did something with exponentiating the numbers but I'm not sure.

Thanks for any help you can give!
There's a picture attached to what we go on step 12
![Screen Shot 2020-09-10 at 7 08 50 PM](https://user-images.githubusercontent.com/70529164/92822238-ef62d900-f399-11ea-8798-3f6e35b1b705.png)

**Comment by phillisd37** [comment]
Here are other pictures of code that we did for steps 1-4 and 5-11, does anyone else have these issues?

Also did we convert the matrix correctly? Or should we use the function unmatrix(x, byrow=FALSE)
![Screen Shot 2020-09-10 at 7 10 54 PM](https://user-images.githubusercontent.com/70529164/92826315-9184c000-f39e-11ea-977b-fd61f97523d2.png)
![Screen Shot 2020-09-10 at 7 20 12 PM](https://user-images.githubusercontent.com/70529164/92826318-921d5680-f39e-11ea-99d0-0025cc7b4353.png)

**Comment by dykesb** [comment]
Not by my computer, but at first glance double check steps 7 and 8. If you're asked to subtract 7 *from* 14, you would do `14 - 7`.

The `NaN` ("not a number" ) leads me to think that you're taking the square root of negative values...

**Comment by dykesb** [comment]
@dykesb the other questions will need to be separate issues.

**Comment by dykesb** [comment]
@phillisd37 your other questions will need to be separate issues.
