### ISSUE TITLE
Activity 1.3 Replace() is not replacing values in my vector

### ISSUE THREAD

**Issue by lefflerl** [STA518-01-Fall20/community#14]
On question 13 of task 4, 'replace all instances of the number 39 with 20', when I run my replace function and then print off the vector afterwards to view the values, it still shows 39 in my vector. 

My code for questions 11-13:
top_secret[38:465] <- round(sqrt(top_secret[38:465]))
top_secret <- replace(top_secret, top_secret==39, 20)
top_secret

Here are some of the values in my vector after the replace():
<img width="477" alt="STA 518 question" src="https://user-images.githubusercontent.com/45080613/93025300-d68d3a00-f5ca-11ea-94ed-708303878df6.PNG">

As you can see, I am still getting 39 in my vector. Thanks for your help!

**Comment by dykesb** [comment]
What does typing `top_secret == 39` in the **Console** produce?

Here is a similar type of example using `replace()` that works for me:

```
> x <- c(1,1,1,9,9,9,1,1)
> x
[1] 1 1 1 9 9 9 1 1
> replace(x, x == 9, 0)
[1] 1 1 1 0 0 0 1 1
```

**Comment by lefflerl** [comment]
Instead of using the Replace(), it seems better to go with top_secret[top_secret == 39] <- 20. Thank you for your help!
