### ISSUE TITLE
Activity 1.3 Task 5

### ISSUE THREAD

**Issue by rossmann8** [STA518-01-Fall20/community#15]
I've tried a few different ways of using my vector as indices for my_symbols, but can't get the message to print out. Here are a couple things I've tried:

my_symbols <- my_symbols[my_vector]
stringr::str_c(my_symbols$Symbol[top_secret], collapse = "")

and 

stringr::str_c(my_symbols[my_vector]$Symbol[top_secret], collapse = "")

Any help would be appreciated!

**Comment by evanwhitmore** [comment]
Try replacing `collapse = ""` with `collapse = NULL`
