### ISSUE TITLE
Project 1 Task 4: 'Perc Species' and 'Perc Overal'

### ISSUE THREAD

**Issue by lefflerl** [STA518-01-Fall20/community#16]
In project 1, task 4, we need to recreate the frequency table. The columns in the table with names 'perc species' and 'perc overal', I don't know where those values come from or what those variables stand for. I know we need to use mutate to create the variable I just don't know what math to do to get their values, or what they mean. Thank you for your help!

![Proj1FreqTable](https://user-images.githubusercontent.com/45080613/93259917-99fa4380-f76e-11ea-858e-7f5768f6ff0a.PNG)

**Comment by dykesb** [comment]
@lefflerl per the directions, you are not allowed to reach out for help through the Community repo for Projects. Please close/delete this Issue.

**Comment by lefflerl** [comment]
Sorry about that. Is there a way to delete it, or I should I just leave it closed?
