### ISSUE TITLE
Activity 3.1 Error

### ISSUE THREAD

**Issue by jenpel** [STA518-01-Fall20/community#22]
When pulling to the main branch, I got an error related to lotr_tidy.csv file and the activity0301-pivoting-data.md file. I have not been able to recreate that error, but it said something about needing to move or change those files because they were duplicates or something similar to that. I slightly changed the names of those files and then I was able to pull from Github. However, once I went though and did the knit, commit, push process, I got the following error in the RMarkdown window: 

processing file: activity0301-pivoting-data.Rmd
Error in parse_block(g[-1], g[1], params.src, markdown_mode) : 
  Duplicate chunk label 'writing_file', which has been used for the chunk:
write_csv(lotr_tidy, "data/lotr_tidy.csv")
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted

**Comment by dykesb** [comment]
The `Duplicate chunk label 'writing_file'` portion of this error leads me to think that you have two code chunks with the same label of `writing_file` (maybe a copy/paste issue). Double check your code chunk labels (the portion at the top of the code chunks like `{r chunk_label}`).

**Comment by jenpel** [comment]
That's what it was. I deleted the duplicate chunk and that error went away.
