### ISSUE TITLE
Activity 4.01

### ISSUE THREAD

**Issue by faskij** [STA518-01-Fall20/community#27]
Bradford,

I am unable to knit my code into a .md document. Even though every chunk of my code works, when R gets to my ggplots, it halts knitting into a .md file. Any suggestions?

-Joe

**Comment by faskij** [comment]
I figured it out. I forgot to delete the 'eval=FALSE' in a previous chunk.

**Comment by dykesb** [comment]
Glad you were able to figure it out!
