### ISSUE TITLE
Dataset 'starwars' doesn't exist

### ISSUE THREAD

**Issue by lefflerl** [STA518-01-Fall20/community#29]
When I load 'tidyverse' and then install and load 'stringr', I still cannot get the dataset starwars to appear. I try to print off the object to see its values and get an error of 'object starwars does not exist'. I will attach a snippet of my code. Thank you for your help!

![Prep Question](https://user-images.githubusercontent.com/45080613/95369141-0b786e00-08a5-11eb-8582-e9d2ec1939ca.PNG)

**Comment by dykesb** [comment]
Try Restarting your R session (first save all work):

1. Session > Restart R. 
2. If (1) does not work, quit your R session by 
  a. Clicking on the big blue R logo in the upper-left-hand corner,
  b. Click on the Quit button next to the appropriate session.

If neither of these resolve the issue, try one of the following:

1. Use the `package::object` call:

```
dplyr::starwars
```

2. Force the data to be loaded into your session:

```
data(starwars)
```

This might also be a R version 4.0.1 issue. You could try changing to R version 3.6.3.

**Comment by lefflerl** [comment]
I was trying to do stringr::starwars and that wasn't working but the dplyr::starwars worked. Thank you!
