### ISSUE TITLE
ACT 0502 replace all original artist

### ISSUE THREAD

**Issue by GibbonKr** [STA518-01-Fall20/community#30]
I just had a question on the endish part of Activity 0502, Im not sure how you wanted us to use replace_all to get rid of the original artist and keep the featured artist only..

i ended up using 

sub('.*featuring', '', artist_credentials)

which worked but not in piping 

but I was wondering how you wanted it done?

**Comment by dykesb** [comment]
If you use `str_replace_all()` (from the `{lubridate}` package) vs. `sub()` (from base R), you can then pipe like you normally would. The start of my pipeline looks like:

```
artist_credentials %>%
  str_replace_all(".* featuring ", "") %>%
  ...
```

**Comment by GibbonKr** [comment]
i get this message
Error: Empty `pattern`` not supported
when i try that

**Comment by GibbonKr** [comment]
awesome- quick followup is there an easier way to do the second part of that same question, besides using a sorted table

**Comment by dykesb** [comment]
@GibbonKr can you ask this as a new issue?
