### ISSUE TITLE
Activity 5.2, task 3

### ISSUE THREAD

**Issue by Abigail-Czinder** [STA518-01-Fall20/community#31]
I can not figure out why this code does not work to split the chart date into three separate columns. I keep getting the error that mutate() can not be applied to a character.

date <- billboard_songs %>%
  as.character('chart date') %>%
  mutate(year = str_sub(chart_date, start = 1, end = 4),
         month = str_sub(chart_date, start = 5, end = 6),
         day = str_sub(chart_date, start = 7, end = 8))
date

**Comment by dykesb** [comment]
Currently, `chart_date` does not exist in your `billboard_songs` dataset. Your `as.character(`chart date`)` should also be within your mutate statement. I renamed it as you seem to be referring to it in year, month, and day.

```
billboard_songs %>%
  mutate(chart_date = as.character('chart date'), 
  year = str_sub(chart_date, start = 1, end = 4),
  month = str_sub(chart_date, start = 5, end = 6),
  day = str_sub(chart_date, start = 7, end = 8))
```
