### ISSUE TITLE
Activity 5.2, task 4

### ISSUE THREAD

**Issue by Abigail-Czinder** [STA518-01-Fall20/community#32]
I can not figure out how to use any of the functions with the 'weeks on chart' column. None of the functions appear to apply. I am met with no errors but the table does not arrange in descending order and there were no columns filtered out. I do not understand what is happening with it.

billboard_songs %>%
  select(title, artist, "weeks on chart") %>%
  filter("weeks on chart" > 15) %>%
  arrange(desc("weeks on chart"))

**Comment by dykesb** [comment]
Since the variable `weeks on chart` has spaces in the variable name, you need to encapsulate it in backticks:

```
`weeks on chart`
```
