### ISSUE TITLE
ACT 05 01

### ISSUE THREAD

**Issue by GibbonKr** [STA518-01-Fall20/community#34]
![Questions](https://user-images.githubusercontent.com/70549557/95521557-d26cf600-0997-11eb-902a-67070cd2b83c.PNG)

why are my bar charts all 1.0?

**Comment by dykesb** [comment]
If you create a bar chart from a frequency table (lines 198-199), you need to specify (set, not map) `stat = "identity" within your `geom_bar()` layer: `geom_bar(aes(x = weekday), stat = "identity")`

Or, you can remove lines 198-199 and your plot will display as you intended.

**Comment by dykesb** [comment]
@GibbonKr please make this title more descriptive for the problem you are having
