### ISSUE TITLE
R Reading in data from the wrong activity data folder.

### ISSUE THREAD

**Issue by pcar13** [STA518-01-Fall20/community#35]
I am trying to finish up activity 501, however when I just opened r and loaded up that file's rmd, it said 
"'/home/carlspai@hpc.gvsu.edu/STA418/activities/activity0502-character-data-dark-violet/data/london_stage_raw.csv' does not exist."
I see in the git window it says activity0502 rmd, even though I have activity 501 open. So I am not sure if it is something wrong in the way I opened it or some glitch in r, but I am not able to load in the london file because r is looking for in the 502 data folder. How do make sure r is looking in the data folder for the activity I want?

**Comment by dykesb** [comment]
Verify that you are in the "activity0501-date-times" project (see image below - I am currently in the "activity0502-character-data" project). If you are not currently in this project, none of the file locations will work. You can switch to a different project by clicking on that area, then selecting the project that you want to be in.

![image](https://user-images.githubusercontent.com/40521287/95598546-0a1e8100-0a1e-11eb-80a8-29d211bc4715.png)
