### ISSUE TITLE
5.1 task 6

### ISSUE THREAD

**Issue by faskij** [STA518-01-Fall20/community#37]
Bradford,

I am confused at what you want for this summary table. When we calculate the total number of events, should the count add to itself as it goes down the table? Should 'min_date' and 'max_date'  be their own columns? The way the directions are written it sounds to me that we want to create new columns called 'min_date', 'max_date', and 'total_events' which would be redundant.
Maybe an example would help. Thanks in advance!

-Joe

**Comment by faskij** [comment]
I ended up grouping by TheatreCode to create the following table:
![image](https://user-images.githubusercontent.com/70581949/95604777-0db60600-0a26-11eb-8793-750670437a81.png)

Is this correct?

**Comment by dykesb** [comment]
`group_by()` was the thing to recognize here! If you want to obtain measures for each `TheatreCode`, you would `group_by(TheatreCode)`. How could you get the dates to show up as the actual earliest/latest date?
