### ISSUE TITLE
5.2 Task 5 Collabaration artists

### ISSUE THREAD

**Issue by lefflerl** [STA518-01-Fall20/community#38]
I currently can't figure out a regular expression in str_extract_all that would give me the artists names that is separated by ',' and '&'. Currently what I have is, ((\\w+\\s*|\\w+)+)(?!=,|&), and it doesn't work very well as it will just grab a single character sometimes. Any help would be appreciated, thank you. 

Here is my code so far:
<img width="272" alt="STA 518 question 5 2" src="https://user-images.githubusercontent.com/45080613/95620982-f7687400-0a3e-11eb-8ebd-908ec43c0833.PNG">

**Comment by dykesb** [comment]
I have `"[^,&]+"`.

> Match characters not (`^`) in the list `[,&]` as many times as needed (`+`).

Since you can use `str_trim()` afterwards, spaces on both sides aren't too important to try to get in `str_extract_all()`.

I like this tool for explaining regex: https://regexr.com/

**Comment by lefflerl** [comment]
That worked perfectly, thank you! I was using that tool cause it helps me a lot as well, I was just making it way too complicated.
