### ISSUE TITLE
Activity 5.2 Task 6 - Artist Collaboration

### ISSUE THREAD

**Issue by reevesjo** [STA518-01-Fall20/community#39]
On the I'm having trouble performing this step on task 6 collab_artist :
- Use `str_extract_all()` to separate entries by `,` or `&`

I currently have:
artist_credentials %>%
  str_replace_all("featuring.*", "") %>%
  str_extract_all("[^,&]+")

I think this str_extract_all statement is extracting all the matches of one or more that are anything but a "," or a "&", but it appears to be excluding some of the artists in the original vector. I would think that this task would be easier accomplished using str_split, so I'm not really sure how to go about it using str_extract_all. Any suggestions?

**Comment by dykesb** [comment]
Is this the same as this? #38

**Comment by reevesjo** [comment]
I didn't see that thread because it was closed. Yes! Thanks so much. Looks like I have the same thing.

**Comment by dykesb** [comment]
Remember from the Readme of this repo:

> Some general advice for opening an Issue on GitHub:
> 
> First search existing issues (open and closed) for answers. If the question already has been answered, you're done! Feel free to open a closed Issue if you believe the answer is not satisfactory.
