### ISSUE TITLE
Viewing Branches as a Graph

### ISSUE THREAD

**Issue by mennengm** [STA518-01-Fall20/community#4]
I cannot find a way to view branches as graphs as described in this [video](https://www.youtube.com/watch?v=oPpnCh7InLY) . Has anyone found another way to view them? This would be really helpful for visualizing the relationships of our branches.

**Comment by dykesb** [comment]
It looks like they've renamed "Graphs" to "Insights" now.

**Comment by nomulac** [comment]
I was having the same issue, I believe that the repository has to either be a team repo or made public.

I went into Insights -> Network (Just an FYI)

You can view [this](https://github.com/STA518-01-Fall20/forking-issues/network)!!
