### ISSUE TITLE
Activity 7.1 - Mutating date columns

### ISSUE THREAD

**Issue by Abigail-Czinder** [STA518-01-Fall20/community#40]
So I want to use the Created and Closed Date columns to find how long each sighting took to become closed. R does not recognize these columns as dates and so I tried to specify that they were dates by using ymd_hms() but this just turns both columns into NA. 

```
Rat_Sightings %>%
  select(`Created Date`, `Closed Date`, Status, City) %>%
  filter(Status == 'Closed') %>%
  mutate(`Created Date` = ymd_hms(`Created Date`),
         `Closed Date` = ymd_hms(`Closed Date`))
```

**Comment by dykesb** [comment]
These two columns are in `"09/04/2015 12:00:00 AM"` or `"mm/dd/yyyy hh:mm:ss"` format. Therefore, you should use `mdy_hms()` instead of `ymd_hms()`.

**Comment by Abigail-Czinder** [comment]
I ran the exact same code as above but using ymd_hms() instead and am still receiving the same results- both date columns filled with NA. This is the error code that I am receiving: "_All formats failed to parse. No formats found.
ℹ Input `Created Date` is `mdy_hms(`Created Date`)`.All formats failed to parse. No formats found.Problem with `mutate()` input `Closed Date`."_
