### ISSUE TITLE
Application 4 DW.2 Duplicates

### ISSUE THREAD

**Issue by lefflerl** [STA518-01-Fall20/community#41]
Are we supposed to list all of the words that have the same score, or only select one of those words. For clarification, there are multiple words with the same familiarity.

**Comment by dykesb** [comment]
You should include ties. In other words, update this to as follows:

> Using the hip-hop dataset, display i) the word(s) that was most *familiar*, on *average*, and ii) the word(s) that was least *familiar*, on *average*, for each of the following demographic groups:
