### ISSUE TITLE
Activity 1.2 Task #3

### ISSUE THREAD

**Issue by phillisd37** [STA518-01-Fall20/community#6]
Hello! I'm having trouble running the code for task #3, I'm wondering if anyone could help?  I got this error, but I'm wondering if I did not put the correct thing for ggplot (data **=mtcars**)? should it be **mpg**? Or do I need to install the package that it says I need to install. Thanks for your help!
![Screen Shot 2020-09-03 at 10 59 09 AM](https://user-images.githubusercontent.com/70529164/92132528-446c8100-edd5-11ea-950e-f5b15802cc2b.png)

**Comment by dykesb** [comment]
I'm going to try to get HPC to update the packages associated with R version 4.0.1 (the default version of R being used on the RStudio Server - my preference is to use this version); however, you can easily change to a previous version of R. To do this, follow this gif:

![change-r-version](https://user-images.githubusercontent.com/40521287/92142729-4721a300-ede2-11ea-96be-e15ef8015f63.gif)

**Comment by reevesjo** [comment]
Just to provide some confirmation, if you switch to the previous version (3.6.3), it will resolve this error and your code should run properly. I just did it with mine and it fixed it!
