### ISSUE TITLE
Activity 1.3 task 4 help

### ISSUE THREAD

**Issue by faskij** [STA518-01-Fall20/community#9]
Bradford,

for this part of the activity, "5. Turn your vector of numbers into a matrix with 5 columns."

Do you want the vector to be repeated in each column or a 13x5 matrix with the last value of column 5 missing?

Thanks in advance.

Sincerely,

Joe

**Comment by dykesb** [comment]
You should take your vector of 955 values (i.e., the `top_secret` object) and "wrap" it to be a matrix with 5 columns (you need to specify this) and 191 rows (you do not need to specify this).

**Comment by faskij** [comment]
Thanks, I am realizing my mistakes now.
